# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)

        # Central Widget of the VectorUI.
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(780, 370, 178, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # Connecting RK4 to the vertical layout widget.
        self.RK4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        # self.RK4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.RK4.setObjectName("RK4")
        self.verticalLayout.addWidget(self.RK4)

        self.MidPoint = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        # self.MidPoint = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.MidPoint.setObjectName("MidPoint")
        self.verticalLayout.addWidget(self.MidPoint)

        # self.ExplicitEuler = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ExplicitEuler = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ExplicitEuler.setObjectName("ExplicitEuler")
        self.verticalLayout.addWidget(self.ExplicitEuler)

        # The interpolation group of buttons. 
        self.interpolationGroup = QtWidgets.QButtonGroup(MainWindow)
        self.interpolationGroup.setObjectName("buttonGroup")

        # Adding 3 buttons to the interpolation group mentioned here.
        self.interpolationGroup.addButton(self.RK4)
        self.interpolationGroup.addButton(self.MidPoint)
        self.interpolationGroup.addButton(self.ExplicitEuler)


        # self.selectMode = QtWidgets.QRadioButton(self.ce
        
        # self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        # self.horizontalSlider_2.setGeometry(QtCore.QRect(870, 250, 91, 21))
        # self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        # self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        
        self.XMin = QtWidgets.QLabel(self.centralwidget)
        self.XMin.setGeometry(QtCore.QRect(810, 250, 67, 17))
        self.XMin.setObjectName("XMin")

        self.XMax = QtWidgets.QLabel(self.centralwidget)
        self.XMax.setGeometry(QtCore.QRect(810, 310, 67, 17))
        self.XMax.setObjectName("XMax")


        # self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        # self.horizontalSlider_3.setGeometry(QtCore.QRect(770, 250, 91, 21))
        # self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        # self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        # self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        # self.horizontalSlider_4.setGeometry(QtCore.QRect(770, 320, 91, 21))
        # self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        # self.horizontalSlider_4.setObjectName("horizontalSlider_4")

        self.yMinSlider = QtWidgets.QSlider(self.centralwidget)
        self.yMinSlider.setGeometry(QtCore.QRect(880, 270, 91, 21))
        self.yMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yMinSlider.setObjectName("yMinSlider")
        
        self.xMinSlider = QtWidgets.QSlider(self.centralwidget)
        self.xMinSlider.setGeometry(QtCore.QRect(760, 270, 91, 21))
        self.xMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xMinSlider.setObjectName("xMinSlider")
        
        self.xMaxSlider = QtWidgets.QSlider(self.centralwidget)
        self.xMaxSlider.setGeometry(QtCore.QRect(760, 320, 91, 21))
        self.xMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xMaxSlider.setObjectName("xMaxSlider")

        # Density slider. 
        self.densitySlider = QtWidgets.QSlider(self.centralwidget)
        self.densitySlider.setGeometry(QtCore.QRect(770, 460, 81, 21))
        self.densitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.densitySlider.setObjectName("densitySlider")

        self.stepSize = QtWidgets.QSlider(self.centralwidget)
        self.stepSize.setGeometry(QtCore.QRect(860, 460, 81, 21))
        self.stepSize.setOrientation(QtCore.Qt.Horizontal)
        self.stepSize.setObjectName("stepSize")
        
        self.yMaxSlider = QtWidgets.QSlider(self.centralwidget)
        self.yMaxSlider.setGeometry(QtCore.QRect(880, 320, 91, 21))
        self.yMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yMaxSlider.setObjectName("yMaxSlider")

        self.YMin = QtWidgets.QLabel(self.centralwidget)
        self.YMin.setGeometry(QtCore.QRect(930, 250, 67, 17))
        self.YMin.setObjectName("YMin")
        
        self.YMax = QtWidgets.QLabel(self.centralwidget)
        self.YMax.setGeometry(QtCore.QRect(930, 310, 67, 17))
        self.YMax.setObjectName("YMax")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(860, 250, 21, 101))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(790, 350, 171, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        
        self.uLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.uLineEdit.setGeometry(QtCore.QRect(760, 100, 201, 27))
        self.uLineEdit.setObjectName("uLineEdit")
        
        self.vLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.vLineEdit.setGeometry(QtCore.QRect(760, 150, 201, 27))
        self.vLineEdit.setObjectName("vLineEdit")

        # Density and Step size label. 
        self.densityLabel = QtWidgets.QLabel(self.centralwidget)
        self.densityLabel.setGeometry(QtCore.QRect(770, 480, 67, 20))
        self.densityLabel.setObjectName("density")

        # Label step size. 
        self.stepSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.stepSizeLabel.setGeometry(QtCore.QRect(860, 480, 67, 20))
        self.stepSizeLabel.setObjectName("stepSizeLabel")
        
        self.uLabel = QtWidgets.QLabel(self.centralwidget)
        self.uLabel.setGeometry(QtCore.QRect(830, 80, 67, 20))
        self.uLabel.setObjectName("uLabel")
        self.vLabel = QtWidgets.QLabel(self.centralwidget)
        self.vLabel.setGeometry(QtCore.QRect(830, 130, 67, 20))
        self.vLabel.setObjectName("vLabel")
        
        self.addPoints = QtWidgets.QRadioButton(self.centralwidget)
        self.addPoints.setGeometry(QtCore.QRect(810, 30, 117, 22))
        self.addPoints.setObjectName("addPoints")
        
        # Button group here. 
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.addPoints)
        self.selectMode = QtWidgets.QRadioButton(self.centralwidget)
        self.selectMode.setGeometry(QtCore.QRect(810, 52, 117, 20))
        self.selectMode.setObjectName("selectMode")
        self.buttonGroup.addButton(self.selectMode)
        self.submitVectorField = QtWidgets.QPushButton(self.centralwidget)
        self.submitVectorField.setGeometry(QtCore.QRect(800, 200, 99, 27))
    
        # Submit vector field.        
        self.submitVectorField.setObjectName("submitVectorField")
        self.startPush = QtWidgets.QRadioButton(self.centralwidget)
        self.startPush.setGeometry(QtCore.QRect(770, 510, 99, 27))
        self.startPush.setObjectName("startPush")
            
        # Stop Push button.
        self.stopPush = QtWidgets.QRadioButton(self.centralwidget)
        self.stopPush.setGeometry(QtCore.QRect(880, 510, 99, 27))
        self.stopPush.setObjectName("stopPush")

        self.animateButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.animateButtonGroup.setObjectName("animate")

        # Start and Stop push button. 
        self.animateButtonGroup.addButton(self.startPush)
        self.animateButtonGroup.addButton(self.stopPush)
        
        # Clear All. 
        self.clearAll = QtWidgets.QPushButton(self.centralwidget)
        self.clearAll.setGeometry(QtCore.QRect(810, 540, 99, 27))
        self.clearAll.setObjectName("clearAll")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Retranslate Ui in this problem. 
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RK4.setText(_translate("MainWindow", "RK4"))
        self.MidPoint.setText(_translate("MainWindow", "MidPoint"))
        self.ExplicitEuler.setText(_translate("MainWindow", "Explicit Euler Method"))
        self.XMin.setText(_translate("MainWindow", "XMin"))
        self.XMax.setText(_translate("MainWindow", "XMax"))
        self.YMin.setText(_translate("MainWindow", "YMin"))
        self.YMax.setText(_translate("MainWindow", "YMax"))
        self.uLabel.setText(_translate("MainWindow", "X"))
        self.vLabel.setText(_translate("MainWindow", "Y"))

        self.stepSizeLabel.setText(_translate("MainWindow", "Step-Size"))
        self.densityLabel.setText(_translate("MainWindow", "Density"))
        self.addPoints.setText(_translate("MainWindow", "Add + Drag"))
        self.selectMode.setText(_translate("MainWindow", "Select Mode"))
        self.submitVectorField.setText(_translate("MainWindow", "Submit"))
        self.startPush.setText(_translate("MainWindow", "Start"))
        self.stopPush.setText(_translate("MainWindow", "Stop"))
        self.clearAll.setText(_translate("MainWindow", "Clear-Points"))
